name: Flutter CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1' # Set your desired Flutter version

    - name: Get Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Firebase (replace with your deployment steps)
      run: |
        # Add your deployment steps here
