name: Flutter CI/CD

on:
  push:
    branches:
      - master

      #dh
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          node-version: '20'
          
          
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Update to Node.js 20
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "12.x"
    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.8' # Set your desired Flutter version
        channel: 'stable' # or 'beta' or 'dev'     
   #     flutter-version: '3.16.5'
    # - name: Setup Flutter
    #   uses: subosito/flutter-action@v2
    #   with:
    #     flutter-version: '3.2.3' # Set your desired Flutter version

    - name: Get Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk
    - uses: actions/upload-artifact@v1
      with:
          name: release-aab
          path: build/app/outputs/apk/release/app-release.apk
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Firebase (replace with your deployment steps)
      run: |
        # Add your deployment steps here
