name: CI

on: 
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
        - develop
        - master
jobs:
  flutter_test:
    name: Run Flutter analyze and test
    runs-on: ubantu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1 
        with: 
          java-version: "12.x"


        
